<a href="https://colab.research.google.com/github/Iffraah96/ShopSense-AI/blob/main/notebook/03_Text_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛍️ ShopSense AI

# Notebook 3: Natural Language Processing (NLP)

## Objective

In this notebook, we will prepare customer review text for machine learning.

Customer reviews are written in natural language, but machine learning models cannot directly understand sentences in the same way humans do.

We will transform the raw review text into a cleaner and more structured format.

### We will learn and perform:

- Loading the cleaned dataset
- Examining raw customer reviews
- Text cleaning
- Lowercase conversion
- Removing punctuation
- Removing unnecessary characters
- Tokenization
- Stopword removal
- Lemmatization
- Creating a cleaned review column
- Comparing raw and cleaned text
- Preparing the text for TF-IDF vectorization

The processed text will be used in the machine learning notebook.

## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import re

import warnings
warnings.filterwarnings("ignore")

## Load Dataset

In [2]:
# Load the cleaned dataset created in Notebook 1
df = pd.read_csv("/content/clean_women_clothing_review_dataset.csv")

# Display the first five reviews
df[["title", "review_text"]].head()

                     title                                        review_text
0                 No Title  Absolutely wonderful - silky and sexy and comf...
1                 No Title  Love this dress!  it's sooo pretty.  i happene...
2  Some major design flaws  I had such high hopes for this dress and reall...
3         My favorite buy!  I love, love, love this jumpsuit. it's fun, fl...
4         Flattering shirt  This shirt is very flattering to all due to th...

## Review Text Cleaning

In [3]:
# Create a Basic Text Cleaning Function

def clean_text(text):
    """
    Clean a customer review by:
    1. Converting text to lowercase
    2. Removing punctuation
    3. Removing extra spaces
    """

    # Convert text to lowercase
    text = text.lower()

    # Remove special characters but keep letters,
    # numbers, spaces, and apostrophes
    text = re.sub(r"[^a-z0-9\s']", "", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

    # Return the cleaned text
    return text

In [4]:
# Clean All Customer Reviews

# Apply cleaning function to every review
df['cleaned_review'] = df['review_text'].apply(clean_text)

# Display the original and cleaned versions
df[["review_text", "cleaned_review"]].head()

,review_text,cleaned_review
0,Absolutely wonderful - silky and sexy and comf...,absolutely wonderful silky and sexy and comfor...
1,Love this dress! it's sooo pretty. i happene...,love this dress it's sooo pretty i happened to...
2,I had such high hopes for this dress and reall...,i had such high hopes for this dress and reall...
3,"I love, love, love this jumpsuit. it's fun, fl...",i love love love this jumpsuit it's fun flirty...
4,This shirt is very flattering to all due to th...,this shirt is very flattering to all due to th...

## Tokenization

In [5]:
# Tokenize Customer Reviews

# Split each cleaned review into individual words
df['tokens'] = df['cleaned_review'].str.split()

# Display the original cleaned review and its tokens
df[["cleaned_review", "tokens"]].head()

,cleaned_review,tokens
0,absolutely wonderful silky and sexy and comfor...,"[absolutely, wonderful, silky, and, sexy, and,..."
1,love this dress it's sooo pretty i happened to...,"[love, this, dress, it's, sooo, pretty, i, hap..."
2,i had such high hopes for this dress and reall...,"[i, had, such, high, hopes, for, this, dress, ..."
3,i love love love this jumpsuit it's fun flirty...,"[i, love, love, love, this, jumpsuit, it's, fu..."
4,this shirt is very flattering to all due to th...,"[this, shirt, is, very, flattering, to, all, d..."

## Stopwords Removal

In [17]:
# Download NLTK Stopwords
import nltk

# Download the English stopword list
nltk.download('stopwords')

# Import the English stopword list
from nltk.corpus import stopwords

# Create a set of English stopwords
stop_words = set(stopwords.words("english"))

# Display a few stopwords
# list(stop_words)[:20]

# ==========================================================
# Keep Important Negation Words


# These words can change the meaning of a review.
important_words = {
    "not", "no", "never", "neither", "nor",
    "it's", "isn't", "don't", "doesn't",
    "didn't", "can't", "couldn't", "won't",
    "wouldn't", "wasn't", "weren't",
    "shouldn't", "hasn't", "haven't", "hadn't"
}

# Remove these important words from the stopword list
# so they are preserved during preprocessing.
stop_words = stop_words - important_words

# Check that "not" is no longer in our stopword list
print("Is 'not' a stopword?", "not" in stop_words)

Is 'not' a stopword? False

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [18]:
# Remove Stopwords from Tokens

# Creating a function to remove stopwords
def remove_stopwords(tokens):
  """
    Remove common stopwords from a list of tokens.
    Important negation words are preserved.
    """

  # Keep only words that are not in our stopword list
  filtered_tokens = [
      word for word in tokens
      if word not in stop_words
  ]
  return filtered_tokens


# Apply the function to all reviews
df["tokens_without_stopwords"] = df["tokens"].apply(remove_stopwords)

# Display the results
df[
    [
        "tokens",
        "tokens_without_stopwords"
    ]
].head()

,tokens,tokens_without_stopwords
0,"[absolutely, wonderful, silky, and, sexy, and,...","[absolutely, wonderful, silky, sexy, comfortable]"
1,"[love, this, dress, it's, sooo, pretty, i, hap...","[love, dress, it's, sooo, pretty, happened, fi..."
2,"[i, had, such, high, hopes, for, this, dress, ...","[high, hopes, dress, really, wanted, work, ini..."
3,"[i, love, love, love, this, jumpsuit, it's, fu...","[love, love, love, jumpsuit, it's, fun, flirty..."
4,"[this, shirt, is, very, flattering, to, all, d...","[shirt, flattering, due, adjustable, front, ti..."

In [19]:
df[
    [
        "cleaned_review",
        "tokens",
        "tokens_without_stopwords"
    ]
].head()

,cleaned_review,tokens,tokens_without_stopwords
0,absolutely wonderful silky and sexy and comfor...,"[absolutely, wonderful, silky, and, sexy, and,...","[absolutely, wonderful, silky, sexy, comfortable]"
1,love this dress it's sooo pretty i happened to...,"[love, this, dress, it's, sooo, pretty, i, hap...","[love, dress, it's, sooo, pretty, happened, fi..."
2,i had such high hopes for this dress and reall...,"[i, had, such, high, hopes, for, this, dress, ...","[high, hopes, dress, really, wanted, work, ini..."
3,i love love love this jumpsuit it's fun flirty...,"[i, love, love, love, this, jumpsuit, it's, fu...","[love, love, love, jumpsuit, it's, fun, flirty..."
4,this shirt is very flattering to all due to th...,"[this, shirt, is, very, flattering, to, all, d...","[shirt, flattering, due, adjustable, front, ti..."

## Lemmatization

Lemmatization converts words into their base or dictionary form.

For example:

- dresses → dress
- fitting → fit
- fits → fit

This reduces variations of the same word and can make text analysis easier.

We will use NLTK's WordNet lemmatizer for this step.

In [20]:
# Download NLTK Resources
import nltk
# Download WordNet, which is used by the lemmatizer
nltk.download('wordnet')

# Download additional WordNet information
nltk.download("omw-1.4")

# Import the WordNet lemmatizer
from nltk.stem import WordNetLemmatizer

# Create the lemmatizer
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [21]:
# Test the Lemmatizer

# Create a small list of example words
example_words = [
    "dresses",
    "fitting",
    "fits",
    "beautiful",
    "flattering"
]

# Lemmatize each word
for word in example_words:
    print(word, "→", lemmatizer.lemmatize(word))

dresses → dress
fitting → fitting
fits → fit
beautiful → beautiful
flattering → flattering

In [22]:
# Create a Lemmatization function

def lemmatized_tokens(tokens):
  '''
  Lemmatize a list of tokens.
  '''

  lemmatized_tokens = [
      lemmatizer.lemmatize(word)
      for word in tokens
  ]

  return lemmatized_tokens

In [23]:
# Lemmatize Customer Reviews

# Apply the lemmatization function to our tokens
df["lemmatized_tokens"] = (
    df["tokens_without_stopwords"]
    .apply(lemmatized_tokens)
)

# Display the results
df[
    [
        "tokens_without_stopwords",
        "lemmatized_tokens"
    ]
].head()

,tokens_without_stopwords,lemmatized_tokens
0,"[absolutely, wonderful, silky, sexy, comfortable]","[absolutely, wonderful, silky, sexy, comfortable]"
1,"[love, dress, it's, sooo, pretty, happened, fi...","[love, dress, it's, sooo, pretty, happened, fi..."
2,"[high, hopes, dress, really, wanted, work, ini...","[high, hope, dress, really, wanted, work, init..."
3,"[love, love, love, jumpsuit, it's, fun, flirty...","[love, love, love, jumpsuit, it's, fun, flirty..."
4,"[shirt, flattering, due, adjustable, front, ti...","[shirt, flattering, due, adjustable, front, ti..."

In [24]:
# Create Final Clean Review Text

# Join the lemmatized words back into a single sentence
df["final_cleaned_review"] = df["lemmatized_tokens"].apply(lambda tokens: " ".join(tokens))

# Display the original and final cleaned reviews
df[
    [
        "review_text",
        "final_cleaned_review"
    ]
].head()

,review_text,final_cleaned_review
0,Absolutely wonderful - silky and sexy and comf...,absolutely wonderful silky sexy comfortable
1,Love this dress! it's sooo pretty. i happene...,love dress it's sooo pretty happened find stor...
2,I had such high hopes for this dress and reall...,high hope dress really wanted work initially o...
3,"I love, love, love this jumpsuit. it's fun, fl...",love love love jumpsuit it's fun flirty fabulo...
4,This shirt is very flattering to all due to th...,shirt flattering due adjustable front tie perf...

## Comparing the review text size before & after preprocessing

In [25]:
# STEP 16: Compare Text Before and After Cleaning

# Calculate the average number of words in the original reviews
original_avg_word_count = (df['review_text'].str.split().str.len().mean())

# Calculate the average number of words after preprocessing
clean_avg_word_count = (df['final_cleaned_review'].str.split().str.len().mean())

# Display the comparison
print(
    "Average words before preprocessing:",
    round(original_avg_word_count, 2)
)

print(
    "Average words after preprocessing:",
    round(clean_avg_word_count, 2)
)

Average words before preprocessing: 60.2
Average words after preprocessing: 29.9